import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.scss']
})
export class HomePageComponent implements OnInit {

  articles = [
    {id: "version-0.3.3-update", title: "Version 0.3.3 Update - Bond of Trust", img:"v033banner.png", text: "New content includes:<ul><li>New Heroes (Erk, Louise, Pent, Sonia, Farina)</li><li>New Skills (G Duel Infantry 4, Atk/Spd Snag, Atk/Spd Ideal)</li><li>New refines (Berserk Armads, Flower Lance, Gáe Bolg, Grima's Truth, Shamshir)</li></ul>"},
    {id: "version-0.3.2-update", title: "Version 0.3.2 Update - Mythic Hero Dagr", img:"v032banner.png", text: "New content includes:<ul><li>New Hero - Mythic Hero Dagr</li><li>New Skills Added (Even Tempest)</li></ul>Also fixed a bug with Spring Duo Myrrhs image - she is now not invisible!", timestamp: "1617086350378"},
    {id: "version-0.3.1-update", title: "Version 0.3.1 Update - Willful Rabbits", img: "v031banner.png", text: "New content includes:<ul><li>New Heroes Added (Severa, Inigo, Myrrh, Minvera, Saleh)</li><li>New Skills Added (R Duel Cavalry, G Duel Flying 4)</li><li>Seals added (Bracing Blow, Spd/Def Solo)</li></ul>Small bug fixes with assets too.", timestamp: "1615965120788"},
    {id: "version-0.3-update", title: "Version 0.3 Update - Seeds of Fodlan + QOL Updates", img: "v03banner.png", text: "New content includes:<ul><li>New Heroes Added (Marianne, Ingrid, Dedue, Linhardt, Solon)</li><li>New Skills Added (B Duel Infantry 4, Atk/Def Near Save)</li><li>New refines added (Grimoire, Ayra's Blade, Ivaldi, Naglfar, Mjolnir)</li></ul>Changes to the website include:<ul><li>Updated Save Image menu to be more efficient, and hopefully fixes some bugs - probably going to have to fix it again</li><li>Changing map has been moved to a dropdown menu</li><li>New pretty buttons for exiting some menus</li><li>New help menu that could help new users</li><li>Reworked add heroes menu to fix bugs and look better</li><li>(some) bugs have been squashed</ul><br />I'm hoping that the next major update will be a lot larger than this one. This also means that it will take longer than this one, so might not be released until around the middle of the year. It'll definitely be worth the wait though :)", timestamp: "1614921532810"},
    {id: "version-0.2.3-update", title: "Version 0.2.3 Update - Legendary Hero Claude", img: "v023banner.png", text: "New content includes:<ul><li>New Hero Added (Claude)</li><li>New Skills Added (Atk/Spd Catch, Fallen Star)</li></ul>Larger update is coming somewhat soon :)", timestamp: "1614323188825"},
    {id: "version-0.2.2-update", title: "Version 0.2.2 Update - Enduring Legacy", img: "v022banner.png", text: "New content includes:<ul><li>New Heroes Added (Azelle, Lex, Annand, Díthorba, Erinys)</li><li>New Skills Added (R Duel Infantry 4, B Duel Flying 4)</li></ul>", timestamp: "1613451897556"},
    {id: "version-0.2.1-update", title: "Version 0.2.1 Update - Love of a King", img: "v021banner.png", text: "<p>Just the banner and refines this time.</p>New content includes:<ul><li>New Heroes Added (Líf & Thrasir, Gustav, Henriette, Veronica, Alfonse)</li><li>New Skills Added (D/R Close Save, A/R Far Save, Def/Res Form, Fatal Smoke)</li><li>New Seals Added (Life & Death, Bracing Stance)</li><li>New Refines Added (Meisterschwert, Spy-song Bow, Giga Excalibur, Audhulma)</li></ul>", timestamp: "1612427881770"},
    {id: "version-0.2-update", title: "Version 0.2 Update - Seiros Mythic Banner + QOL Updates", img: "v02banner.png", text: "<p>Larger update this time. Including a few important requested features.</p>Firstly, new content: <ul><li>New Heroes Added (Seiros)</li><li>New Skills Added (Dragon Wall 3, Wings of Light)</li><li>New Weapons Added (Aurora Breath)</li></ul><p>Large numbers of small changes include:</p><ul><li>Moved to HTTPS</li><li>Added a toggleable grid overlay on AR-D Builder</li><li>Added dragging ranges for heroes/structures</li><li>Added asset/flaw colors to the unit build table</li><li>Added dragonflower icon next to count on table</li><li>Added unit/movement type icons to units on grid (toggleable)</li><li>Added UI Icons to buttons</li><li>Added github issues link in report a bug</li><li>Added drag boundary so you can't drag structures/heroes into the abyss</li><li>This page!</li><li>Settings page (will have more settings in the future)</li><li>Image saving - including adding unit builds to the image</li><li>7 Heroes can now be added provided you have a mythic hero that allows you to (i.e. currently just Seiros)</li><li>Heroes now show visibly as resplendent on the map</li></ul><p>Bug fixes include:</p><ul><li>Fixed being able to place structures on defense tiles</li><li>Fixed the resplendent toggle always being off in the edit build menu (even if the hero was set to repslendent on)</li></ul><p>A lot of features for this update came from ideas suggested to me through <a href='https://discord.gg/z9YSeEqzg4' target='_blank'>discord</a>, if you have any useful feedback or just want to chat feel free to drop by.", timestamp: "1611808388015"},
    {id: "version-0.1.2-update", title: "Version 0.1.2 Update - Dark Desert Rituals", img: "v012banner.png", text: "<p>Small content patch.</p>New content includes:<ul><li>New Heroes Added (Dorothea & Lene, Tharja, Raphael, Katarina, Kris)</li><li>New Skills Added (Def/Res Chill, Swift Impact)</li><li>New Seals Added (Brazen Spd/Def, Air Orders)</ul>", timestamp: "1610952749000"},
    {id: "version-0.1.1-update", title: "Version 0.1.1 Update - Shared Purpose", img: "v011banner.png", text: "<p>Content patch - nothing new website wise.</p>New content includes:<ul><li>New Heroes Added (Sara, Rowan, Asbel, Miranda, Veld)</li><li>New Skills Added (Close Ward, Seal Atk/Res, Spd/Res Oath, Swift Stance 3)</li><li>New Weapons Added (Grafcalibur, Indignant Bow, Kia Staff, Arden's Blade, Springtime Staff)<li>New Refines Added (Arden's Blade, Springtime Staff, Forseti, Warrior Princess)</ul>Small bug fixes:<ul><li>Added skill icons for Atk/Def Snag and Res Cantrip</li><li>Fixed Falchion refine issue</li></ul>", timestamp: "1609991958488"}
  ];
  constructor() { }

  ngOnInit(): void {

  }

}
